name: brepmatching
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.9
  - pytorch::pytorch=1.10
  - conda-forge::cudatoolkit>=11,<12
  - pyg::pyg=2.0
  - conda-forge::numpy=1.23
  - conda-forge::pandas=1.4
  - conda-forge::pyarrow=8.0
  - conda-forge::scipy=1.8
  - conda-forge::scikit-learn=1.1
  - conda-forge::tqdm=4.64
  - conda-forge::matplotlib=3.5
  - conda-forge::dotmap=1.3
  - conda-forge::meshplot=0.4
  - ipykernel
  - conda-forge::eigen=3.4
  - conda-forge::occt=7.6
  - conda-forge::cmake=3.23
  - conda-forge::pybind11=2.9
  - conda-forge::pip=22.1
  - conda-forge::tensorboard=2.10
  - conda-forge::pytorch-lightning=1.6
  - pip:
    - xxhash
    - pyrender
    - git+https://github.com/degravity/automate.git@v1.0.4

